### ISSUE TITLE
Consider adding helper functions for easy initialization

### ISSUE THREAD

**Issue by carlosalberto** [lightstep/opentelemetry-exporter-java#1]
Consider adding a pair of functions to help users of the LS exporter, as per [Jaeger exporter routines](https://github.com/open-telemetry/opentelemetry-java/pull/977/files), namely:

1. Add a function to easily install the exporter in `OpenTelemetry.getTracerProvider()` (potentially with some nice default settings).
2. Add a function to detect parameters from env vars & system properties and create a LS Exporter out of it.

**Comment by malafeev** [comment]
@carlosalberto we need to define env vars. Something like:
```
LS_ACCESS_TOKEN
LS_COLLECTOR_HOST
LS_COLLECTOR_PORT
LS_COLLECTOR_PROTOCOL
LS_COMPONENT_NAME
```
?

**Comment by malafeev** [comment]
done

**Comment by carlosalberto** [comment]
Hey @malafeev Thanks for working on this. I will want to eventually have System properties as a potential thing (might not need it now, but it might come handy later on). I will create a new ticket to track that though.

Thanks for working on this!
