### ISSUE TITLE
Deployment to Bintray/Maven Central

### ISSUE THREAD

**Issue by carlosalberto** [lightstep/opentelemetry-exporter-java#2]
As of now, we haven't released any artifact to Maven Central (which would be nice, even if it's a preview).

@malafeev is there any reason preventing us from doing so? Or is it only iterations we need to pour to make it happen?

**Comment by malafeev** [comment]
Currently it is based on snapshot version of OTel api.
Should we start to use released version?

**Comment by carlosalberto** [comment]
This is done, closing.
