### ISSUE TITLE
Add/clean up tests for the new predefined LS attributes

### ISSUE THREAD

**Issue by carlosalberto** [lightstep/opentelemetry-exporter-java#37]
We need to add tests for new predefined tags (`service.version` and `lightstep.hostname`), while probably removing the overloads in `Adapter` that do not take `Collection<KeyValue> lsSpanAttributes`.

**Comment by malafeev** [comment]
partially done.

**Comment by malafeev** [comment]
I added tests to LightstepSpanExporterTest.java for service.version and lightstep.hostname

**Comment by malafeev** [comment]
actually done
