### ISSUE TITLE
Review Resource/Reporter handling

### ISSUE THREAD

**Issue by carlosalberto** [lightstep/opentelemetry-exporter-java#47]
How to handle the tags.

**Comment by malafeev** [comment]
Sounds like create reporter per resource. 
1. Resource is available per `SpanData`. 
1. On each call `export(Collection<SpanData> spans)` we get several spans with several resources. 
1. Then for each resource create own reporter and use it to send particular spans.

My concern is performance. 
- Can we cache reporters? 
- On each call `export(Collection<SpanData> spans)` create new set of reporters?

**Comment by kayousterhout** [comment]
Closing this because this repo is now deprecated.
